[package]
name = "llhttp"
version = "0.1.0"
authors = ["Jack Liar"]
edition = "2018"

[dependencies]
libc = "0.2"
llhttp-sys = { version = "0.0.1", path = "../llhttp-sys" }

[features]
gen = ["llhttp-sys/gen"]
static = ["llhttp-sys/static"]
